### ISSUE TITLE
Cyanogenmod-11

### ISSUE THREAD

**Issue by IKGapirov** [syphyr/cm_build_scripts#3]
Good day!
I'm sorry for disturbing you.
Great works, thanks for u for the hard work.
I tried to build CM-11 and using your manifest, everything fine, but when I enter google account get it....

`Can`t establish a reliable connection to the server.`
Please can u advise something about this?
Thank you in advance!

**Comment by syphyr** [comment]
Make sure that https://github.com/syphyr/android/commits/cm-11.0 is in sync with .repo/manifests

The problem is you are not getting the new ca certs defined in the android repo.

**Comment by IKGapirov** [comment]
Thank you very much for answering.
I think I understand you, I will try..

**Comment by syphyr** [comment]
That command you used to sync is fine. There is just a known issue with repo that sometimes .repo/manifests does not get synced with the android repo when the android repo is changed.

**Comment by syphyr** [comment]
Just cd to .repo/manifests and cherry pick all the missing manifest changes

**Comment by IKGapirov** [comment]
By the way I wanted to ask, did you get such an error when building?

> external/libxml2/parser.c:11773: error: undefined reference to 'xmlHaltParser'
> collect2: error: ld returned 1 exit status

And I deleted this line https://github.com/syphyr/android_external_libxml2/blob/cm-11.0/parser.c#L11773
Or is there a solution?

**Comment by syphyr** [comment]
There should not be any errors. These are the steps I used to setup a build environment:

1) repo init -u https://github.com/CyanogenMod/android.git -b cm-11.0 --depth=1
2) repo sync
3) Add local manifest changes
4) repo sync
5) Make sure .repo/manifests is current with new changes to "android" repo
6) repo sync
7) build

Initially setting up the build environment can be a little tricky because of all the repo changes needed from the local manifest. The original cyanogen repos also need to sync one time before adding the local manifest changes so all the directories get created.

**Comment by IKGapirov** [comment]
> Just cd to .repo/manifests and cherry pick all the missing manifest changes

Happened
Now it turns out to log into Google account.
Thanks a lot for your advice.

**Comment by IKGapirov** [comment]
> Initially setting up the build environment can be a little tricky because of all the repo changes needed from the local manifest. The original cyanogen repos also need to sync one time before adding the local manifest changes so all the directories get created.

[**All perfectly**](https://imgur.com/a/DVv8RJI)!
Thanks again!
